name: mvk_app
description: "MVK mobil alkalmazás - modern közösségi közlekedési menetrend és járatkövetés"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI és Material Design
  material_symbols_icons: ^4.2780.0
  
  # Animációk
  flutter_animate: ^4.5.0
  rive: ^0.13.1
  lottie: ^3.1.2
  animated_text_kit: ^4.2.3
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  page_transition: ^2.1.0
  
  # Állapotkezelés és architektúra
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.7.0
  injectable: ^2.4.2
  freezed_annotation: ^2.4.3
  auto_route: ^7.9.2
  
  # Hálózat és adatkezelés
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  http: ^1.1.0
  
  # Térkép és helymeghatározás
  google_maps_flutter: ^2.6.1
  flutter_map: ^8.1.1
  geolocator: ^11.0.0
  
  # Egyéb UI komponensek
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  
  cupertino_icons: ^1.0.8
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  font_awesome_flutter: ^10.8.0
  animated_toggle_switch: ^0.8.5
  glass_kit: ^4.0.1
  gradient_borders: ^1.0.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^10.1.2
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  auto_route_generator: ^7.3.2
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/rive/
    - mvkzrt/

  # A Material Design alapértelmezett fontjait használjuk
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
